name: CI Workflow for building Micronaut CRUD Application

on:
  push:
    branches:
      - jdbc

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: abcd1234
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --host=localhost --user=root --password=abcd1234"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Create Database
        run: mysql --host=127.0.0.1 --user=root --password=abcd1234 -e "CREATE DATABASE IF NOT EXISTS micronaut_crud;"

      - name: Build and Run Test
        run: ./gradlew clean build

      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: micronaut-crud-jar
          path: build/libs/*.jar

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: micronaut-crud-jar
          path: build/libs

      - name: Get Version
        run: echo "VERSION=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV


      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}